# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'simple-weather-app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire', '~> 4.7'
	pod 'SwiftyJSON', '~> 4.0'

  # Pods for simple-weather-app

  target 'simple-weather-appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'simple-weather-appUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
